import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { renderArticle } from './seo-extra.mjs';

const out = 'dist';
const site = 'https://newyorkhut.com';
const updated = '2026-08-26';

const pages = [
  { slug:'ny-hut-renewal-guide', title:'NY HUT Renewal Guide: Certificates, Decals, and Timing', desc:'Learn how New York HUT renewals work, what is replaced during a renewal series, and what carriers should verify before operating.', category:'Renewals', body:`<p>New York may require carriers to renew HUT certificates of registration and decals. Renewal is a credential-management event, not a substitute for resolving overdue returns, unpaid tax, or incorrect vehicle information.</p><h2>What is renewed?</h2><p>When the Tax Department requires renewal, it issues new certificates and decals to replace outstanding credentials. The state renewal fee is currently $1.50 per vehicle and includes both the certificate and decal.</p><h2>What should carriers review first?</h2><ul><li>Legal name, taxpayer information, and HUT account status</li><li>VIN, plate, vehicle weight, and fleet assignments</li><li>Outstanding HUT returns or balances</li><li>Vehicles that were sold, transferred, junked, or removed from service</li></ul><h2>Do not assume an old decal remains valid</h2><p>Follow the dates and instructions for the applicable credential series. A new series can require replacement of prior credentials even when the underlying HUT account remains open.</p>` },
  { slug:'ny-hut-decal-replacement', title:'NY HUT Decal Replacement: Lost, Damaged, or Destroyed Credentials', desc:'How to replace a lost or damaged New York HUT decal or certificate using OSCAR or Form TMT-334.', category:'Credentials', body:`<p>A HUT decal is issued to a particular vehicle and cannot be transferred to another vehicle. If a decal or certificate is lost, mutilated, or destroyed, request a replacement rather than moving another vehicle's decal.</p><h2>Replacement options</h2><p>New York permits replacement requests through OSCAR or Form TMT-334, Application for Duplicate and/or Replacement Highway Use Tax and/or Automotive Fuel Certificates and Decals.</p><h2>Current state fee</h2><p>The replacement fee is $1.50 per vehicle and includes both a certificate of registration and decal.</p><h2>Where is the decal displayed?</h2><p>For a truck, tractor, or other self-propelled vehicle, New York instructs carriers to affix the decal securely and conspicuously on the body, including the bumper, as near as possible to the front license plate.</p>` },
  { slug:'ny-hut-registration-cost', title:'NY HUT Registration Cost: State Fees and Service Charges Explained', desc:'Understand the New York state credential fee, trip-certificate fee, replacement fee, and why service-company pricing is separate.', category:'Costs', body:`<p>“NY HUT cost” can refer to several different expenses. Separate the state credential fee, any tax ultimately owed, and any optional service-company charge.</p><h2>Permanent certificate and decal</h2><p>The New York state fee for a HUT certificate of registration and decal is currently $1.50 per vehicle.</p><h2>Replacement credential</h2><p>The state replacement fee is also $1.50 per vehicle when a certificate or decal is lost, damaged, or destroyed.</p><h2>Trip certificate</h2><p>The New York state fee for a HUT trip certificate is $25. A permit service company may charge its own service fee in addition to the state fee.</p><h2>Highway use tax is separate</h2><p>The credential fee does not represent the carrier's future HUT liability. Permanent registrants generally have mileage-based return and payment obligations.</p>` },
  { slug:'ny-hut-trip-certificate-limits', title:'NY HUT Trip Certificate Limits: Validity, Annual Maximum, and Records', desc:'Review the three-day operating window, annual ten-certificate limit, record retention, and restrictions for New York HUT trip certificates.', category:'Temporary Permits', body:`<p>A HUT trip certificate is designed for occasional New York operation. It should not be treated as an unlimited replacement for permanent registration.</p><h2>Validity window</h2><p>The certificate permits operation until midnight of the third day after its issue date. Saturdays, Sundays, and public holidays do not extend the expiration.</p><h2>Annual maximum</h2><p>A carrier may not apply for more than ten HUT trip certificates during a calendar year.</p><h2>Carry and retain the certificate</h2><p>Carry a copy in the covered vehicle. New York also requires carriers to keep copies for at least four years to substantiate compliance.</p><h2>Important restriction</h2><p>HUT trip certificates are not available for trucks, trailers, dollies, or attached devices transporting automotive fuel under the circumstances described by New York.</p>` },
  { slug:'ny-hut-leased-trucks', title:'NY HUT for Leased Trucks: Lessor, Lessee, and 30-Day Rules', desc:'Understand when a lessee may need separate New York HUT credentials even if the vehicle owner already has a certificate and decal.', category:'Leased Vehicles', body:`<p>Leasing a truck does not automatically shift every HUT obligation to the owner. New York focuses on who controls and operates the vehicle and how long the lease lasts.</p><h2>Leases longer than 30 days</h2><p>If the lease or agreement covers more than 30 consecutive days, the lessee generally must obtain a certificate and decal unless the vehicle will operate in New York for ten days or less.</p><h2>Leases of 30 days or less</h2><p>New York states that a lessee is not required to obtain a certificate and decal when the lease agreement is for 30 days or less.</p><h2>The owner's credential may not be enough</h2><p>Even when the lessor already has credentials for the truck, the lessee may need credentials valid for the term of the lease. Retain the lease agreement and records establishing who controlled the vehicle.</p>` },
  { slug:'ny-hut-temporary-plates', title:'NY HUT for Temporary Plates: Credential and Vehicle Information Checklist', desc:'Learn how temporary plate details fit into a New York HUT credential request and what must be updated when registration information changes.', category:'Registration', body:`<p>A temporary license plate does not by itself eliminate HUT requirements. The carrier should accurately report the plate jurisdiction and temporary plate information available when requesting the credential.</p><h2>HUT and vehicle registration are separate</h2><p>HUT eligibility depends primarily on vehicle weight, configuration, use, and applicable exemptions—not simply whether the current plate is temporary.</p><h2>Update changed information</h2><p>New York requires carriers to report changes in plate information and certain vehicle-weight changes. OSCAR can be used to revise HUT credentials.</p><h2>Keep supporting documents</h2><p>Retain the temporary registration, plate expiration information, VIN documentation, lease documents when applicable, and the HUT credential issued for the vehicle.</p>` },
  { slug:'ny-hut-canadian-carriers', title:'NY HUT for Canadian Carriers Entering New York', desc:'Canadian carriers can need New York HUT credentials in addition to IFTA and apportioned registration. Review permanent and occasional-use paths.', category:'Out-of-State Carriers', body:`<p>A Canadian base jurisdiction does not exempt a qualifying truck from New York HUT. The same New York weight, vehicle-use, and exemption analysis applies when the carrier enters New York.</p><h2>IFTA does not replace HUT</h2><p>Canadian provinces participate in IFTA, but IFTA addresses fuel-use tax reporting. New York HUT is a separate highway-use tax and credential program.</p><h2>Apportioned registration does not replace HUT</h2><p>An IRP or apportioned plate also does not satisfy New York HUT requirements by itself.</p><h2>Occasional versus recurring operation</h2><p>An occasional operator may consider a trip certificate, subject to the validity and annual limits. Regular New York operations generally warrant review of permanent registration and ongoing HUT filing duties.</p>` },
  { slug:'ny-hut-penalties', title:'NY HUT Penalties: Operating, Filing, and Payment Violations', desc:'Review New York civil fines for operating without required HUT credentials and the penalties that can apply to late returns or unpaid tax.', category:'Enforcement', body:`<p>HUT enforcement can involve both roadside credential violations and account-level filing or payment problems.</p><h2>Operating without required credentials</h2><p>After notice and an opportunity for a hearing, New York states that operating without a required certificate or decal can result in a civil fine of $500 to $2,000 for a first violation.</p><h2>Repeat violations</h2><p>A second or subsequent violation within three years of a prior finding can result in a civil fine of $1,000 to $3,500.</p><h2>Late returns and tax</h2><p>Late filing or payment can also generate penalties and interest. New York currently describes a penalty of 10% of tax due plus 1% for each additional month or part of a month, subject to the stated 30% maximum.</p><h2>Credential consequences</h2><p>Failure to file required returns or pay tax can contribute to denial, suspension, or revocation of HUT credentials.</p>` },
  { slug:'ny-hut-audit-guide', title:'NY HUT Audit Guide: Preparing Mileage and Vehicle Records', desc:'Learn what records support a New York HUT return and how carriers can prepare for a mileage, vehicle, or credential review.', category:'Audits', body:`<p>A HUT audit tests whether reported New York mileage, vehicle classifications, weight methods, and tax calculations are supported by contemporaneous records.</p><h2>Build a consistent record trail</h2><ul><li>Trip reports, dispatch records, and routes</li><li>Odometer or hubometer readings</li><li>Fuel and toll records</li><li>Vehicle registrations, leases, and credential history</li><li>Filed MT-903 returns and calculation workpapers</li></ul><h2>Reconcile before an audit</h2><p>Mileage totals should reconcile across dispatch, electronic logging, fuel, toll, and tax-return records. Investigate unexplained gaps rather than creating estimates after the fact.</p><h2>Trip certificates</h2><p>Keep each trip certificate for at least four years and identify the vehicle and dates it covered so those miles are not confused with permanent-registration activity.</p>` },
  { slug:'ny-hut-recordkeeping-requirements', title:'NY HUT Recordkeeping Requirements: Mileage, Vehicles, and Returns', desc:'A practical checklist for maintaining mileage and vehicle records that support New York Highway Use Tax filings.', category:'Recordkeeping', body:`<p>Permanent HUT registration creates an ongoing obligation to support the miles and tax reported. Reliable records also help the carrier distinguish taxable mileage, excluded operations, and trip-certificate periods.</p><h2>Mileage records</h2><p>Maintain trip-level information showing dates, origins and destinations, routes, New York mileage, and beginning and ending odometer or hubometer readings when used.</p><h2>Vehicle records</h2><p>Keep VIN, plate, registered and operating weight information, vehicle type, ownership or lease documents, certificate history, and decal information.</p><h2>Return support</h2><p>Retain copies of filed returns, schedules, payment confirmations, adjustment calculations, and the source records used to prepare each return.</p><h2>Retention discipline</h2><p>New York expressly requires copies of HUT trip certificates to be retained for at least four years. Apply a documented retention schedule to the broader supporting record set and confirm current requirements for the carrier's circumstances.</p>` }
];

for (const page of pages) {
  const path = join(out, page.slug, 'index.html');
  await mkdir(dirname(path), { recursive:true });
  await writeFile(path, renderArticle(page));
}

const sitemapPath = join(out, 'sitemap.xml');
let sitemap = await readFile(sitemapPath, 'utf8');
const additions = pages.map((page) => `  <url><loc>${site}/${page.slug}/</loc><lastmod>${updated}</lastmod><changefreq>monthly</changefreq><priority>0.8</priority></url>`).join('\n');
sitemap = sitemap.replace('</urlset>', `${additions}\n</urlset>`);
await writeFile(sitemapPath, sitemap);

const homePath = join(out, 'index.html');
let home = await readFile(homePath, 'utf8');
const cards = pages.map((page, index) => `<div class="card"><div class="card-top"><span class="card-icon">${['REN','RPL','$','3D','LSE','TMP','CAN','FINE','AUD','REC'][index]}</span><span class="card-number">${String(index + 15).padStart(2,'0')}</span></div><div class="eyebrow">${page.category}</div><h3>${page.title}</h3><p>${page.desc}</p><a href="/${page.slug}/">Read the guide →</a></div>`).join('');
const section = `<section class="section"><div class="section-kicker">Carrier compliance library</div><h2>Renewals, leased vehicles, enforcement, and records</h2><p class="lead">The next layer of New York HUT guidance for managing credentials and staying prepared after registration.</p><div class="grid">${cards}</div></section>`;
home = home.replace('<section class="conversion">', `${section}<section class="conversion">`);
home = home.replace('<strong>18</strong><span>Focused authority pages</span>', '<strong>28</strong><span>Focused authority pages</span>');
await writeFile(homePath, home);

console.log(`Added ${pages.length} second-wave authority pages.`);

export { renderArticle };
